chore: cleaning and refactoring - make it easy to source it
Signed-off-by: Daniel Liszka <daniel@chainloop.dev>

diff --git a/tools/c8l b/tools/c8l
--- a/tools/c8l
+++ b/tools/c8l
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.8 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -31,6 +31,7 @@ c8l_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Show help about a command\n" "help   "
   printf "  %s   [i] Inspect.\n" "inspect"
+  printf "  %s   Show the content of c8l script ready for sourcing.\n" "source "
   printf "  %s   Chainloop CLI UX improved\n" "cli    "
   echo
 
@@ -93,6 +94,32 @@ c8l_inspect_usage() {
   printf "%s\n" "Usage:"
   printf "  c8l inspect\n"
   printf "  c8l inspect --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+c8l_source_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "c8l source - Show the content of c8l script ready for sourcing.\n"
+    echo
+
+  else
+    printf "c8l source - Show the content of c8l script ready for sourcing.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  c8l source\n"
+  printf "  c8l source --help | -h\n"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -772,22 +799,28 @@ install_chainloop_tools() {
 
 chainloop_attestation_add_from_yaml() {
   log "Adding Metadata files based on .chainloop.yml to attestation"
-  script=$(cat .chainloop.yml | yq eval '.attestation[] | "chainloop attestation add --name "  + .name + " --value " + .path + " 2>&1; "')
+  script=$(cat .chainloop.yml | yq eval '.attestation[] | "chainloop attestation add --name "  + .name + " --value " + .path + " --remote-state --attestation-id ${ATT_ID} 2>&1; "')
   eval $script
 }
 
 chainloop_attestation_init() {
   log "Initializing Chainloop Attestation"
-  if [ -z "${CHAINLOOP_CONTRACT_REVISION}" ]; then
-    chainloop attestation init -f 2>&1
-  else
-    chainloop attestation init -f --contract-revision ${CHAINLOOP_CONTRACT_REVISION} 2>&1
+  CR_VALUE=""
+  if [ -n "${CHAINLOOP_CONTRACT_REVISION}" ]; then
+    CR_VALUE="--contract-revision ${CHAINLOOP_CONTRACT_REVISION}"
   fi
+  r=$(chainloop attestation init -f --remote-state --output json $CR_VALUE 2>&1)
+  if [ $? -ne 0 ]; then
+    log_error "Chainloop initialization failed"
+    exit 1
+  fi
+  ATT_ID=$(echo $r | jq -r '.attestationID')
+  log "Attestation ID: $ATT_ID"
 }
 
 chainloop_attestation_status() {
   log "Checking Attestation Status"
-  if chainloop attestation status --full &>c8-status.txt; then
+  if chainloop attestation status --full --remote-state --attestation-id "${ATT_ID}" &>c8-status.txt; then
     log "Attestation Status Process Completed Successfully"
     cat c8-status.txt
   else
@@ -800,6 +833,12 @@ chainloop_attestation_status() {
 
 chainloop_attestation_push() {
   log "Pushing Attestation"
+  if [ -n "${CHAINLOOP_USE_INSECURE_KEY}" ]; then
+    log "# USING INSECURE KEY BECAUSE CHAINLOOP_USE_INSECURE_KEY is set"
+    CHAINLOOP_SIGNING_KEY_PATH="cosign.key"
+    CHAINLOOP_SIGNING_PASSWORD="insecure"
+    echo $CHAINLOOP_SIGNING_KEY | cosign generate-key-pair
+  fi
   if [ -z "${CHAINLOOP_SIGNING_KEY_PATH+x}" ]; then
     log "  with CHAINLOOP_SIGNING_KEY"
     tmp_key="${CHAINLOOP_TMP_DIR}/key"
@@ -810,7 +849,7 @@ chainloop_attestation_push() {
     tmp_key="${CHAINLOOP_SIGNING_KEY_PATH}"
   fi
   # chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY
-  if chainloop attestation push --key $tmp_key &>c8-push.txt; then
+  if chainloop attestation push --key $tmp_key --remote-state --attestation-id "${ATT_ID}" &>c8-push.txt; then
     log "Attestation Process Completed Successfully"
     cat c8-push.txt
     rm $tmp_key
@@ -895,16 +934,6 @@ install_chainloop_labs_cli() {
   $SUDO_CMD chmod +x /usr/local/bin/c8l
 }
 
-install_labs_helpers() {
-  log "Installing Chainloop Labs Helpers"
-  branch=${1:-main}
-  curl -sfL https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/src/lib/chainloop.sh -o ~/chainloop.sh
-  if [ $? -ne 0 ]; then
-    log_error "Failed to install labs helpers"
-    return 1
-  fi
-}
-
 install_chainloop_labs() {
   log "Installing Chainloop Labs"
   branch=${1:-main}
@@ -912,7 +941,14 @@ install_chainloop_labs() {
   mkdir -p ${CHAINLOOP_TMP_DIR}
 
   install_chainloop_labs_cli ${branch}
-  install_labs_helpers ${branch}
+}
+
+# how to use it:
+#   source <(c8l source)
+source_chainloop_labs() {
+  log "Sourcing Chainloop Labs"
+  script_path=$(readlink -f "$0")
+  cat $script_path | sed '$d' | sed '$d'
 }
 
 print_in_color() {
@@ -998,6 +1034,12 @@ c8l_inspect_command() {
 
   l "\n\n CAS Backends"
   chainloop cas-backend list -o json
+}
+
+c8l_source_command() {
+  validate_env
+  source_chainloop_labs
+
 }
 
 c8l_cli_install_tools_command() {
@@ -1189,6 +1231,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    source)
+      action="source"
+      shift
+      c8l_source_parse_requirements "$@"
+      shift $#
+      ;;
+
     cli | c)
       action="cli"
       shift
@@ -1287,6 +1336,46 @@ c8l_inspect_parse_requirements() {
   done
 
   action="inspect"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+c8l_source_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        c8l_source_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  action="source"
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1672,7 +1761,6 @@ c8l_cli_get_attestations_parse_requirements() {
       *)
 
         if [[ -z ${args['sha']+x} ]]; then
-
           args['sha']=$1
           shift
         else
@@ -1718,7 +1806,6 @@ c8l_cli_get_parse_requirements() {
       *)
 
         if [[ -z ${args['sha']+x} ]]; then
-
           args['sha']=$1
           shift
         else
@@ -1764,7 +1851,6 @@ c8l_cli_workflow_get_parse_requirements() {
       *)
 
         if [[ -z ${args['uuid']+x} ]]; then
-
           args['uuid']=$1
           shift
         else
@@ -1850,7 +1936,6 @@ c8l_cli_workflow_run_get_parse_requirements() {
       *)
 
         if [[ -z ${args['uuid']+x} ]]; then
-
           args['uuid']=$1
           shift
         else
@@ -1924,6 +2009,7 @@ run() {
   case "$action" in
     "help") c8l_help_command ;;
     "inspect") c8l_inspect_command ;;
+    "source") c8l_source_command ;;
     "cli") c8l_cli_command ;;
     "cli install-tools") c8l_cli_install_tools_command ;;
     "cli attestation-add-from-yaml") c8l_cli_attestation_add_from_yaml_command ;;
