Refactoring Chainloop Labs (#21)
Signed-off-by: Daniel Liszka <daniel@chainloop.dev>

diff --git a/tools/c8l b/tools/c8l
--- a/tools/c8l
+++ b/tools/c8l
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.8 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -531,11 +531,14 @@ c8l_cli_workflow_run_list_usage() {
 }
 
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -546,6 +549,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -554,57 +560,7 @@ normalize_input() {
   done
 }
 
-data_path=/tmp/chainloop/data
-mkdir -p "$data_path"
-
-store_attestation_uuid() {
-    sha256="$1"
-    uuid="$2"
-    name="$3"
-    mkdir -p "${data_path}/$sha256"
-    echo "$uuid $name" >> "${data_path}/$sha256/uuids.txt"
-}
-
-get_attestations_uuids() {
-    sha256="$1"
-    if [[ -f "${data_path}/$sha256/uuids.txt" ]]; then
-        cat "${data_path}/$sha256/uuids.txt"
-    else
-        echo "No attestations found for SHA256: $sha256"
-    fi
-}
-
-print_in_color() {
-  local color="$1"
-  shift
-  if [[ -z ${NO_COLOR+x} ]]; then
-    printf "$color%b\e[0m\n" "$*"
-  else
-    printf "%b\n" "$*"
-  fi
-}
-
-red() { print_in_color "\e[31m" "$*"; }
-green() { print_in_color "\e[32m" "$*"; }
-yellow() { print_in_color "\e[33m" "$*"; }
-blue() { print_in_color "\e[34m" "$*"; }
-magenta() { print_in_color "\e[35m" "$*"; }
-cyan() { print_in_color "\e[36m" "$*"; }
-bold() { print_in_color "\e[1m" "$*"; }
-underlined() { print_in_color "\e[4m" "$*"; }
-red_bold() { print_in_color "\e[1;31m" "$*"; }
-green_bold() { print_in_color "\e[1;32m" "$*"; }
-yellow_bold() { print_in_color "\e[1;33m" "$*"; }
-blue_bold() { print_in_color "\e[1;34m" "$*"; }
-magenta_bold() { print_in_color "\e[1;35m" "$*"; }
-cyan_bold() { print_in_color "\e[1;36m" "$*"; }
-red_underlined() { print_in_color "\e[4;31m" "$*"; }
-green_underlined() { print_in_color "\e[4;32m" "$*"; }
-yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
-blue_underlined() { print_in_color "\e[4;34m" "$*"; }
-magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
-cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
-
+export CHAINLOOP_BIN_PATH="${CHAINLOOP_BIN_PATH:-/usr/local/bin/chainloop}"
 
 is_chainloop_in_path() {
   if command -v chainloop &>/dev/null; then
@@ -617,19 +573,19 @@ is_chainloop_in_path() {
 }
 
 validate_env() {
-  if [ ! is_chainloop_in_path ]; then
+  is_chainloop_in_path
+  if [ ! $? ]; then
     exit 1
   fi
 }
 
-l() {
-  yellow "$*"
-}
-
-# helpers
 t=$(date "+%Y%m%d%H%M%S")
 script_dir="$(cd "$(dirname "$0")" && pwd)"
 CHAINLOOP_TMP_DIR="${CHAINLOOP_TMP_DIR:-${script_dir}/tmp/chainloop}"
+
+l() {
+  yellow "$*"
+}
 
 log() {
   # echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*"
@@ -644,42 +600,16 @@ log_header() {
   blue_bold "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*"
 }
 
-validate_chainloop_required_env_vars() {
-  if [ -z "${CHAINLOOP_ROBOT_ACCOUNT}" ]; then
-    log_error "CHAINLOOP_ROBOT_ACCOUNT is not set"
+prepare_tmp_file() {
+  tmp_dir="${CHAINLOOP_TMP_DIR}"
+  file_name=$1
+  mkdir -p "${tmp_dir}"
+  t="${tmp_dir}/${file_name}"
+  if [ -f $t ]; then
+    echo "Temporary file file $t already exists"
     return 1
   fi
-  if [ -z "${CHAINLOOP_VERSION+x}" ]; then
-    CHAINLOOP_VERSION=""
-  fi
-  if [ -z "${CHAINLOOP_SIGNING_KEY}" ]; then
-    log_error "CHAINLOOP_SIGNING_KEY is not set"
-    return 1
-  fi
-  if [[ -z "${CHAINLOOP_SIGNING_PASSWORD+x}" ]]; then
-    log_error "CHAINLOOP_SIGNING_PASSWORD is not set"
-    return 1
-  fi
-}
-
-export CHAINLOOP_BIN_PATH="${CHAINLOOP_BIN_PATH:-/usr/local/bin/chainloop}"
-
-chainloop_bin_install() {
-  # it takes the list of paths and installs them in the CHAINLOOP_BIN_PATH
-  # it creates the directory if it does not exist
-  # it makes the files executable
-  # make sure to detect the basename of the path and properly make the target file executable
-  mkdir -p $CHAINLOOP_BIN_PATH
-  for path in $@; do
-    if [ -f $path ]; then
-      log "Installing $path"
-      cp $path $CHAINLOOP_BIN_PATH
-      chmod +x $CHAINLOOP_BIN_PATH/$(basename $path)
-    else
-      log_error "chainloop_bin_install: path $path does not exist"
-      return 1
-    fi
-  done
+  echo $t
 }
 
 # chainloop_bin_cache_in_dir - it takes a path and copy there the CHAINLOOP_BIN_PATH
@@ -766,11 +696,78 @@ chainloop_restore_all_from_cache() {
   chainloop_bin_install $cache_dir/*
 }
 
+validate_chainloop_required_env_vars() {
+  if [ -z "${CHAINLOOP_ROBOT_ACCOUNT}" ]; then
+    log_error "CHAINLOOP_ROBOT_ACCOUNT is not set"
+    return 1
+  fi
+  if [ -z "${CHAINLOOP_VERSION+x}" ]; then
+    CHAINLOOP_VERSION=""
+  fi
+  if [ -z "${CHAINLOOP_SIGNING_KEY}" ]; then
+    log_error "CHAINLOOP_SIGNING_KEY is not set"
+    return 1
+  fi
+  if [[ -z "${CHAINLOOP_SIGNING_PASSWORD+x}" ]]; then
+    log_error "CHAINLOOP_SIGNING_PASSWORD is not set"
+    return 1
+  fi
+}
+
+install_chainloop_labs() {
+  mkdir -p ${CHAINLOOP_TMP_DIR}
+  branch=${1:-main}
+  generic_install c8l https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/c8l
+}
+
+# how to use it:
+#   source <(c8l source)
+source_chainloop_labs() {
+  script_path=$(readlink -f "$0")
+  echo "export PATH=\"/usr/local/bin:$CHAINLOOP_BIN_PATH:$PATH\""
+  cat $script_path | sed '$d' | sed '$d'
+}
+
+chainloop_bin_install() {
+  # it takes the list of paths and installs them in the CHAINLOOP_BIN_PATH
+  # it creates the directory if it does not exist
+  # it makes the files executable
+  # make sure to detect the basename of the path and properly make the target file executable
+  mkdir -p $CHAINLOOP_BIN_PATH
+  for path in "$@"; do
+    if [ -f $path ]; then
+      log "Installing $path"
+      cp $path $CHAINLOOP_BIN_PATH
+      chmod +x $CHAINLOOP_BIN_PATH/$(basename $path)
+    else
+      log_error "chainloop_bin_install: path $path does not exist"
+      return 1
+    fi
+  done
+}
+
+install_chainloop_cli() {
+  mkdir -p ${CHAINLOOP_TMP_DIR} $CHAINLOOP_BIN_PATH
+  log "Installing Chainloop CLI"
+  url_chainloop_cli="https://raw.githubusercontent.com/chainloop-dev/chainloop/eb53f4e8ce3c35251553efc77b7e04e792b2c992/docs/static/install.sh"
+  if [ -n "${CHAINLOOP_VERSION}" ]; then
+    curl -sfL "${url_chainloop_cli}" | bash -s -- --version v${CHAINLOOP_VERSION} --path $CHAINLOOP_BIN_PATH
+  else
+    curl -sfL "${url_chainloop_cli}" | bash -s -- --path $CHAINLOOP_BIN_PATH
+  fi
+  if [ $? -ne 0 ]; then
+    log_error "Chainloop installation failed"
+    return 1
+  fi
+}
+
 
 # chainloop_install takes the list of tools and installs them with functions below install_${name}
 chainloop_install() {
-  for tool in $@; do
-    install_${tool}
+  for tool in "$@"; do
+    if ! "install_${tool}" ;  then
+      return 1
+    fi
   done
 }
 
@@ -789,99 +786,6 @@ generic_install() {
   chmod +x $file_path
 }
 
-install_chainloop_cli() {
-  mkdir -p ${CHAINLOOP_TMP_DIR} $CHAINLOOP_BIN_PATH
-  log "Installing Chainloop CLI"
-  if [ -n "${CHAINLOOP_VERSION}" ]; then
-    curl -sfL https://docs.chainloop.dev/install.sh | bash -s -- --version v${CHAINLOOP_VERSION} --path $CHAINLOOP_BIN_PATH
-  else
-    curl -sfL https://docs.chainloop.dev/install.sh | bash -s -- --path $CHAINLOOP_BIN_PATH
-  fi
-  if [ $? -ne 0 ]; then
-    log_error "Chainloop installation failed"
-    return 1
-  fi
-}
-
-install_cosign() {
-  generic_install cosign https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
-}
-
-install_chainloop_cli_and_cosign() {
-  install_cosign
-  install_chainloop_cli
-}
-
-install_syft() {
-  log "Installing Syft"
-  curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $CHAINLOOP_BIN_PATH
-  if [ $? -ne 0 ]; then
-    log_error "Syft installation failed"
-    return 1
-  fi
-}
-
-install_semgrep() {
-  log "Installing Semgrep"
-  python3 -m pip install semgrep -q >$CHAINLOOP_TMP_DIR/install_semgrep.log
-  if [ $? -ne 0 ]; then
-    log_error "Semgrep installation failed"
-    return 1
-  fi
-}
-
-install_conftest() {
-  LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
-  wget -q "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz" >$CHAINLOOP_TMP_DIR/install_wget.log
-  tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
-  $SUDO_CMD mv conftest $CHAINLOOP_BIN_PATH
-}
-
-install_oras() {
-  log "Installing Oras"
-  VERSION="1.0.0"
-  curl -sLO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
-  mkdir -p oras-install/
-  tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
-  $SUDO_CMD mv oras-install/oras $CHAINLOOP_BIN_PATH
-  rm -rf oras_${VERSION}_*.tar.gz oras-install/
-  oras version
-  if [ $? -ne 0 ]; then
-    log_error "Oras installation failed"
-    return 1
-  fi
-}
-
-install_jq() {
-  log "Installing jq"
-  $SUDO_CMD apt-get install jq -y >$CHAINLOOP_TMP_DIR/install_jq.log
-  if [ $? -ne 0 ]; then
-    log_error "jq installation failed"
-    return 1
-  fi
-}
-
-install_ruby_restclient() {
-  log "Installing Ruby rest-client"
-  $SUDO_CMD gem install rest-client >$CHAINLOOP_TMP_DIR/install_ruby_restclient.log
-  if [ $? -ne 0 ]; then
-    log_error "rest-client installation failed"
-    return 1
-  fi
-}
-
-install_yq() {
-  generic_install yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
-}
-
-install_parlay() {
-  log "Installing Parlay"
-  wget -q https://github.com/snyk/parlay/releases/latest/download/parlay_Linux_x86_64.tar.gz >$CHAINLOOP_TMP_DIR/install_parlay.log
-  tar -xvf parlay_Linux_x86_64.tar.gz
-  $SUDO_CMD mv parlay $CHAINLOOP_BIN_PATH
-  rm parlay_Linux_x86_64.tar.gz
-}
-
 spdx2cyclonedx() {
   spdx_file=$1
   cyclonedx_file=$2
@@ -892,35 +796,6 @@ spdx2cyclonedx() {
   fi
 }
 
-install_chainloop_tools() {
-  log_header "Installing Chainloop Tools"
-  export PATH=$CHAINLOOP_BIN_PATH:$PATH
-
-  if [ -f $CHAINLOOP_BIN_PATH/chainloop ]; then
-    log "Skipping... Chainloop Tools already installed"
-    return 0
-  fi
-
-  install_chainloop_cli_and_cosign
-  install_syft
-  install_semgrep
-  install_oras
-  install_jq
-  install_yq
-  install_parlay
-}
-
-
-chainloop_attestation_add_from_yaml() {
-  export ATTESTATION_NAME=$1
-  if [ -z "${ATTESTATION_NAME}" ]; then
-    export ATTESTATION_NAME="attestation"
-  fi
-  log "Adding Metadata files based on .chainloop.yml"
-  script=$(cat .chainloop.yml | yq eval '.[strenv(ATTESTATION_NAME)][] | "chainloop attestation add --name "  + .name + " --value " + .path + " --remote-state --attestation-id ${CHAINLOOP_ATTESTATION_ID} 2>&1; "')
-  log $script
-  eval $script
-}
 
 chainloop_attestation_init() {
   log "Initializing Chainloop Attestation"
@@ -982,18 +857,6 @@ chainloop_attestation_push() {
   fi
 }
 
-prepare_tmp_file() {
-  tmp_dir="${CHAINLOOP_TMP_DIR}"
-  file_name=$1
-  mkdir -p "${tmp_dir}"
-  t="${tmp_dir}/${file_name}"
-  if [ -f $t ]; then
-    echo "Temporary file file $t already exists"
-    return 1
-  fi
-  echo $t
-}
-
 chainloop_summary() {
   tmpfile=$(prepare_tmp_file report.txt)
   if [ $? -ne 0 ]; then
@@ -1014,12 +877,8 @@ chainloop_summary() {
   rm $tmpfile
 }
 
-chainloop_generate_github_summary() {
-  log "Generating GitHub Summary"
-  chainloop_summary >>$GITHUB_STEP_SUMMARY
-}
-
 chainloop_summary_on_failure() {
+  log "Generating Summary on Failure"
   tmpfile=$(prepare_tmp_file report_on_failure.txt)
   echo -e "## Chainloop Attestation Failed\nWe were unable to complete the Chainloop attestation process due to unmet SecOps and Compliance requirements:" >>$tmpfile
   if [ -f c8-push.txt ]; then
@@ -1036,8 +895,12 @@ chainloop_summary_on_failure() {
   rm $tmpfile
 }
 
+
+chainloop_generate_github_summary() {
+  chainloop_summary >>$GITHUB_STEP_SUMMARY
+}
+
 chainloop_generate_github_summary_on_failure() {
-  log "Generating GitHub Summary on Failure"
   chainloop_summary_on_failure >>$GITHUB_STEP_SUMMARY
 }
 
@@ -1052,18 +915,15 @@ chainloop_collect_logs_for_github_jobs() {
   done
 }
 
-install_chainloop_labs() {
-  mkdir -p ${CHAINLOOP_TMP_DIR}
-  branch=${1:-main}
-  generic_install c8l https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/c8l
-}
-
-# how to use it:
-#   source <(c8l source)
-source_chainloop_labs() {
-  script_path=$(readlink -f "$0")
-  echo "export PATH=\"/usr/local/bin:$CHAINLOOP_BIN_PATH:$PATH\""
-  cat $script_path | sed '$d' | sed '$d'
+chainloop_attestation_add_from_yaml() {
+  export ATTESTATION_NAME=$1
+  if [ -z "${ATTESTATION_NAME}" ]; then
+    export ATTESTATION_NAME="attestation"
+  fi
+  log "Adding Metadata files based on .chainloop.yml"
+  script=$(cat .chainloop.yml | yq eval '.[strenv(ATTESTATION_NAME)][] | "chainloop attestation add --name "  + .name + " --value " + .path + " --remote-state --attestation-id ${CHAINLOOP_ATTESTATION_ID} 2>&1; "')
+  log $script
+  eval $script
 }
 
 print_in_color() {
@@ -1097,25 +957,97 @@ blue_underlined() { print_in_color "\e[4;34m" "$*"; }
 magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
-yaml_load() {
-  local prefix=$2
-  local s='[[:space:]]*' w='[a-zA-Z0-9_]*'
-  local fs
 
-  fs=$(echo @ | tr @ '\034')
+install_chainloop_tools() {
+  log_header "Installing Chainloop Tools"
+  export PATH=$CHAINLOOP_BIN_PATH:$PATH
 
-  sed -ne "s|^\($s\):|\1|" \
-    -e "s|^\($s\)\($w\)$s:${s}[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
-    -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
-    awk -F"$fs" '{
-      indent = length($1)/2;
-      vname[indent] = $2;
-      for (i in vname) {if (i > indent) {delete vname[i]}}
-      if (length($3) > 0) {
-         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
-         printf("%s%s%s=\"%s\"\n", "'"$prefix"'",vn, $2, $3);
-      }
-    }'
+  if [ -f $CHAINLOOP_BIN_PATH/chainloop ]; then
+    log "Skipping... Chainloop Tools already installed"
+    return 0
+  fi
+
+  install_chainloop_cli_and_cosign
+  install_syft
+  install_semgrep
+  install_oras
+  install_jq
+  install_yq
+  install_parlay
+}
+
+install_cosign() {
+  generic_install cosign https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
+}
+
+install_chainloop_cli_and_cosign() {
+  install_cosign
+  install_chainloop_cli
+}
+
+install_syft() {
+  log "Installing Syft"
+  curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $CHAINLOOP_BIN_PATH
+  if [ $? -ne 0 ]; then
+    log_error "Syft installation failed"
+    return 1
+  fi
+}
+
+install_semgrep() {
+  log "Installing Semgrep"
+  python3 -m pip install semgrep -q >$CHAINLOOP_TMP_DIR/install_semgrep.log
+  if [ $? -ne 0 ]; then
+    log_error "Semgrep installation failed"
+    return 1
+  fi
+}
+
+install_conftest() {
+  LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
+  wget -q "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz" >$CHAINLOOP_TMP_DIR/install_wget.log
+  tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
+  $SUDO_CMD mv conftest $CHAINLOOP_BIN_PATH
+}
+
+install_oras() {
+  log "Installing Oras"
+  VERSION="1.0.0"
+  curl -sLO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
+  mkdir -p oras-install/
+  tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
+  $SUDO_CMD mv oras-install/oras $CHAINLOOP_BIN_PATH
+  rm -rf oras_${VERSION}_*.tar.gz oras-install/
+  oras version
+  if [ $? -ne 0 ]; then
+    log_error "Oras installation failed"
+    return 1
+  fi
+}
+
+install_jq() {
+  generic_install jq https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64
+}
+
+install_ruby_restclient() {
+  log "Installing Ruby rest-client"
+  $SUDO_CMD gem install rest-client >$CHAINLOOP_TMP_DIR/install_ruby_restclient.log
+  if [ $? -ne 0 ]; then
+    log_error "rest-client installation failed"
+    return 1
+  fi
+}
+
+install_yq() {
+  generic_install yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
+}
+
+install_parlay() {
+  log "Installing Parlay"
+  wget -q https://github.com/snyk/parlay/releases/latest/download/parlay_Linux_x86_64.tar.gz >$CHAINLOOP_TMP_DIR/install_parlay.log
+  tar -xvf parlay_Linux_x86_64.tar.gz
+  $SUDO_CMD mv parlay $CHAINLOOP_BIN_PATH
+  rm parlay_Linux_x86_64.tar.gz
 }
 
 c8l_help_command() {
@@ -1152,7 +1084,6 @@ c8l_inspect_command() {
 }
 
 c8l_source_command() {
-  validate_env
   source_chainloop_labs
 
 }
