chore(ci): improving a reusable workflow: working on sh helpers
Signed-off-by: Daniel Liszka <daniel@chainloop.dev>

diff --git a/tools/c8l b/tools/c8l
--- a/tools/c8l
+++ b/tools/c8l
@@ -554,26 +554,6 @@ inspect_args() {
 
 }
 
-is_chainloop_in_path() {
-  if command -v chainloop &> /dev/null; then
-    # we are good
-    return 0
-  else
-    log "chainloop is not in PATH, install it."
-    return 1
-  fi
-}
-
-validate_env() {
-    if [ ! is_chainloop_in_path ] ; then
-        exit 1
-    fi
-}
-
-l() {
-  yellow "$*"
-}
-
 data_path=/tmp/chainloop/data
 mkdir -p "$data_path"
 
@@ -594,9 +574,62 @@ get_attestations_uuids() {
     fi
 }
 
+print_in_color() {
+  local color="$1"
+  shift
+  if [[ -z ${NO_COLOR+x} ]]; then
+    printf "$color%b\e[0m\n" "$*"
+  else
+    printf "%b\n" "$*"
+  fi
+}
+
+red() { print_in_color "\e[31m" "$*"; }
+green() { print_in_color "\e[32m" "$*"; }
+yellow() { print_in_color "\e[33m" "$*"; }
+blue() { print_in_color "\e[34m" "$*"; }
+magenta() { print_in_color "\e[35m" "$*"; }
+cyan() { print_in_color "\e[36m" "$*"; }
+bold() { print_in_color "\e[1m" "$*"; }
+underlined() { print_in_color "\e[4m" "$*"; }
+red_bold() { print_in_color "\e[1;31m" "$*"; }
+green_bold() { print_in_color "\e[1;32m" "$*"; }
+yellow_bold() { print_in_color "\e[1;33m" "$*"; }
+blue_bold() { print_in_color "\e[1;34m" "$*"; }
+magenta_bold() { print_in_color "\e[1;35m" "$*"; }
+cyan_bold() { print_in_color "\e[1;36m" "$*"; }
+red_underlined() { print_in_color "\e[4;31m" "$*"; }
+green_underlined() { print_in_color "\e[4;32m" "$*"; }
+yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
+blue_underlined() { print_in_color "\e[4;34m" "$*"; }
+magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
+cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
+
+
+is_chainloop_in_path() {
+  if command -v chainloop &> /dev/null; then
+    # we are good
+    return 0
+  else
+    log "chainloop is not in PATH, install it."
+    return 1
+  fi
+}
+
+validate_env() {
+    if [ ! is_chainloop_in_path ] ; then
+        exit 1
+    fi
+}
+
+l() {
+  yellow "$*"
+}
+
 # helpers
 t=$(date "+%Y%m%d%H%M%S")
 script_dir="$(cd "$(dirname "$0")" && pwd)"
+CHAINLOOP_TMP_DIR="${CHAINLOOP_TMP_DIR:-${script_dir}/tmp/chainloop}"
 
 log() {
   # echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*"
@@ -629,22 +662,9 @@ validate_chainloop_required_env_vars() {
   fi
 }
 
-install_chainloop_tools() {
-  log_header "Installing Chainloop Tools"
-  export PATH=/usr/local/bin:$PATH
 
-  if [ -f /usr/local/bin/chainloop ]; then
-    log "Skipping... Chainloop Tools already installed"
-    return 0
-  fi
-
-  curl -sL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
-  if [ $? -ne 0 ]; then
-    log_error "Cosign installation failed"
-    return 1
-  fi
-  chmod +x /usr/local/bin/cosign
-
+install_chainloop_cli() {
+  mkdir -p $CHAINLOOP_TMP_DIR
   log "Installing Chainloop CLI"
   if [ -n "${CHAINLOOP_VERSION}" ]; then
     curl -sfL https://docs.chainloop.dev/install.sh | bash -s -- --version v${CHAINLOOP_VERSION}
@@ -655,19 +675,52 @@ install_chainloop_tools() {
     log_error "Chainloop installation failed"
     return 1
   fi
+}
 
-  log "Installing Syft, Oras, Cosign, and jq"
+install_cosign() {
+  log "Installing Cosign"
+  curl -sfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
+  if [ $? -ne 0 ]; then
+    log_error "Cosign installation failed"
+    return 1
+  fi
+  chmod +x /usr/local/bin/cosign
+}
 
+install_chainloop_cli_and_cosign() {
+  install_cosign
+  install_chainloop_cli
+}
+
+install_syft() {
+  log "Installing Syft"
   curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
   if [ $? -ne 0 ]; then
     log_error "Syft installation failed"
     return 1
   fi
+}
 
-  python3 -m pip install semgrep
+install_semgrep() {
+  log "Installing Semgrep"
+  python3 -m pip install semgrep -q > $CHAINLOOP_TMP_DIR/install_semgrep.log
+  if [ $? -ne 0 ]; then
+    log_error "Semgrep installation failed"
+    return 1
+  fi
+}
 
+install_conftest() {
+  LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
+  wget -q "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz" > $CHAINLOOP_TMP_DIR/install_wget.log
+  tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
+  sudo mv conftest /usr/local/bin
+}
+
+install_oras() {
+  log "Installing Oras"
   VERSION="1.0.0"
-  curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
+  curl -sLO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
   mkdir -p oras-install/
   tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
   sudo mv oras-install/oras /usr/local/bin/
@@ -677,24 +730,39 @@ install_chainloop_tools() {
     log_error "Oras installation failed"
     return 1
   fi
+}
 
-  sudo apt-get install jq ruby -y
+install_jq() {
+  log "Installing jq"
+  sudo apt-get install jq -y > $CHAINLOOP_TMP_DIR/install_jq.log
   if [ $? -ne 0 ]; then
     log_error "jq installation failed"
     return 1
   fi
+}
 
-  sudo gem install rest-client
+install_ruby_restclient() {
+  log "Installing Ruby rest-client"
+  sudo gem install rest-client > $CHAINLOOP_TMP_DIR/install_ruby_restclient.log
+  if [ $? -ne 0 ]; then
+    log_error "rest-client installation failed"
+    return 1
+  fi
+}
 
+install_yq() {
+  log "Installing yq"
   sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
-  sudo chmod a+x /usr/local/bin/yq
   if [ $? -ne 0 ]; then
     log_error "yq installation failed"
     return 1
   fi
+  sudo chmod a+x /usr/local/bin/yq
+}
 
+install_parlay() {
   log "Installing Parlay"
-  wget https://github.com/snyk/parlay/releases/download/v0.2.0/parlay_Linux_x86_64.tar.gz
+  wget -q https://github.com/snyk/parlay/releases/latest/download/parlay_Linux_x86_64.tar.gz > $CHAINLOOP_TMP_DIR/install_parlay.log
   tar -xvf parlay_Linux_x86_64.tar.gz
   sudo mv parlay /usr/local/bin/
   rm parlay_Linux_x86_64.tar.gz
@@ -709,6 +777,25 @@ spdx2cyclonedx() {
     return 1
   fi
 }
+
+install_chainloop_tools() {
+  log_header "Installing Chainloop Tools"
+  export PATH=/usr/local/bin:$PATH
+
+  if [ -f /usr/local/bin/chainloop ]; then
+    log "Skipping... Chainloop Tools already installed"
+    return 0
+  fi
+
+  install_chainloop_cli_and_cosign
+  install_syft
+  install_semgrep
+  install_oras
+  install_jq
+  install_yq
+  install_parlay
+}
+
 
 process_metadata() {
   log "Preparing metadata for $artifact"
@@ -809,7 +896,7 @@ chainloop_adapter_run() {
     log_header "Processing ${kind} ${repo} - artifacts $artifacts"
     log_header "  processing artifact: $app_id - $full_uri"
     log "Initializing Chainloop Attestation"
-    chainloop attestation init -f # --contract-revision 1
+    chainloop attestation init
     if [ $? -ne 0 ]; then
       log_error "Chainloop initialization failed"
       exit 1
@@ -842,30 +929,124 @@ chainloop_adapter_run() {
 }
 
 chainloop_attestation_add_from_yaml() {
+  log "Adding Metadata files based on .chainloop.yml to attestation"
   script=`cat .chainloop.yml | yq eval '.attestation[] | "chainloop attestation add --name "  + .name + " --value " + .path + "; "'`
   eval $script
 }
 
+chainloop_attestation_init() {
+  log "Initializing Chainloop Attestation"
+  if [ -z "${CHAINLOOP_CONTRACT_REVISION+x}" ]; then
+    chainloop attestation init -f
+  else
+    chainloop attestation init -f --contract-revision ${CHAINLOOP_CONTRACT_REVISION}
+  fi
+}
+
 chainloop_attestation_status() {
-  chainloop attestation status --full &> c8-status.txt
-  cat c8-status.txt
+  log "Checking Attestation Status"
+  if chainloop attestation status --full &> c8-status.txt ; then
+    log "Attestation Status Process Completed Successfully"
+    cat c8-status.txt
+  else
+    exit_code=$?
+    log_error "Attestation Status Process Failed"
+    cat c8-status.txt
+    return $exit_code
+  fi
 }
 
 chainloop_attestation_push() {
-  chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY &> c8-push.txt
-  cat c8-push.txt
+  log "Pushing Attestation"
+  if chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY &> c8-push.txt ; then
+    log "Attestation Process Completed Successfully"
+    cat c8-push.txt
+  else
+    exit_code=$?
+    log_error "Attestation Process Failed"
+    cat c8-push.txt
+    return $exit_code
+  fi
+}
+
+chainloop_summary() {
+  mkdir -p ${CHAINLOOP_TMP_DIR}
+  tmpfile="${CHAINLOOP_TMP_DIR}/report.txt"
+  digest=`cat c8-push.txt| grep " Digest: " | awk -F\  '{print $3}'`
+  echo -e "## Great job!\nYou are making SecOps and Compliance teams really happy. Keep up the good work!\n" >> $tmpfile
+  echo "**[Chainloop Trust Report](https://app.chainloop.dev/attestation/${digest})**" >> $tmpfile
+  echo "\`\`\`" >> $tmpfile
+  cat c8-status.txt >> $tmpfile
+  echo "\`\`\`" >> $tmpfile
+  cat $tmpfile
 }
 
 chainloop_generate_github_summary() {
-  digest=`cat c8-push.txt| grep " Digest: " | awk -F\  '{print $3}'`
-  echo -e "## Great job!\nYou are making SecOps and Compliance teams really happy. Keep up the good work!\n" >> $GITHUB_STEP_SUMMARY
-  echo "**[Chainloop Trust Report](https://app.chainloop.dev/attestation/${digest})**" >> $GITHUB_STEP_SUMMARY
+  log "Generating GitHub Summary"
+  chainloop_summary >> $GITHUB_STEP_SUMMARY
+}
 
-  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+chainloop_summary_on_failure() {
+  mkdir -p ${CHAINLOOP_TMP_DIR}
+  tmpfile="${CHAINLOOP_TMP_DIR}/report_on_failure.txt"
+  echo -e "## Chainloop Attestation Failed\nWe were unable to complete the Chainloop attestation process due to unmet SecOps and Compliance requirements:" >> $tmpfile
+  if [ -f c8-push.txt ]; then
+    echo -e "\n> [!WARNING]" >> $tmpfile
+    cat c8-push.txt | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" | sed 's/^/> /' >> $tmpfile
+    echo -e "\n" >> $tmpfile
+  fi
+  if [ -f c8-status.txt ]; then
+    echo "\`\`\`" >> $tmpfile
+    cat c8-status.txt | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" >> $tmpfile
+    echo "\`\`\`" >> $tmpfile
+  fi
+  cat $tmpfile
+}
 
-  cat c8-status.txt >> $GITHUB_STEP_SUMMARY
-  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+chainloop_generate_github_summary_on_failure() {
+  log "Generating GitHub Summary on Failure"
+  chainloop_summary_on_failure >> $GITHUB_STEP_SUMMARY
+}
 
+chainloop_collect_logs_for_github_jobs() {
+  log "Collecting logs for GitHub Jobs"
+  # requires GH_TOKEN github.token
+
+  # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#download-job-logs-for-a-workflow-run
+  mkdir -p metadata/gh_logs
+  gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs > metadata/gh_logs/jobs.json
+  for j in `cat metadata/gh_logs/jobs.json | jq '.jobs[].id'` ; do
+    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/jobs/${j}/logs > metadata/gh_logs/${j}.log
+  done
+}
+
+install_chainloop_labs_cli() {
+  log "Installing Chainloop Labs CLI"
+  mkdir -p metadata
+  branch=${1:-main}
+  sudo curl -sfL https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/c8l -o /usr/local/bin/c8l
+  if [ $? -ne 0 ]; then
+    log_error "Failed to install labs CLI"
+    return 1
+  fi
+  sudo chmod +x /usr/local/bin/c8l
+}
+
+install_labs_helpers() {
+  log "Installing Chainloop Labs Helpers"
+  branch=${1:-main}
+  curl -sfL https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/src/lib/chainloop.sh -o ~/chainloop.sh
+  if [ $? -ne 0 ]; then
+    log_error "Failed to install labs helpers"
+    return 1
+  fi
+}
+
+install_chainloop_labs() {
+  logs "Installing Chainloop Labs"
+  branch=${1:-main}
+  install_chainloop_labs_cli ${branch}
+  install_labs_helpers ${branch}
 }
 
 print_in_color() {
