chore: cleaning and refactoring
Signed-off-by: Daniel Liszka <daniel@chainloop.dev>

diff --git a/tools/c8l b/tools/c8l
--- a/tools/c8l
+++ b/tools/c8l
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -527,33 +527,6 @@ normalize_input() {
   done
 }
 
-inspect_args() {
-  if ((${#args[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
-    echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
-  else
-    echo args: none
-  fi
-
-  if ((${#other_args[@]})); then
-    echo
-    echo other_args:
-    echo "- \${other_args[*]} = ${other_args[*]}"
-    for i in "${!other_args[@]}"; do
-      echo "- \${other_args[$i]} = ${other_args[$i]}"
-    done
-  fi
-
-  if ((${#deps[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
-    echo
-    echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
-  fi
-
-}
-
 data_path=/tmp/chainloop/data
 mkdir -p "$data_path"
 
@@ -607,7 +580,7 @@ cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
 
 is_chainloop_in_path() {
-  if command -v chainloop &> /dev/null; then
+  if command -v chainloop &>/dev/null; then
     # we are good
     return 0
   else
@@ -617,9 +590,9 @@ is_chainloop_in_path() {
 }
 
 validate_env() {
-    if [ ! is_chainloop_in_path ] ; then
-        exit 1
-    fi
+  if [ ! is_chainloop_in_path ]; then
+    exit 1
+  fi
 }
 
 l() {
@@ -664,7 +637,7 @@ validate_chainloop_required_env_vars() {
 
 
 install_chainloop_cli() {
-  mkdir -p $CHAINLOOP_TMP_DIR
+  mkdir -p ${CHAINLOOP_TMP_DIR}
   log "Installing Chainloop CLI"
   if [ -n "${CHAINLOOP_VERSION}" ]; then
     curl -sfL https://docs.chainloop.dev/install.sh | bash -s -- --version v${CHAINLOOP_VERSION}
@@ -703,7 +676,7 @@ install_syft() {
 
 install_semgrep() {
   log "Installing Semgrep"
-  python3 -m pip install semgrep -q > $CHAINLOOP_TMP_DIR/install_semgrep.log
+  python3 -m pip install semgrep -q >$CHAINLOOP_TMP_DIR/install_semgrep.log
   if [ $? -ne 0 ]; then
     log_error "Semgrep installation failed"
     return 1
@@ -712,9 +685,9 @@ install_semgrep() {
 
 install_conftest() {
   LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
-  wget -q "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz" > $CHAINLOOP_TMP_DIR/install_wget.log
+  wget -q "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz" >$CHAINLOOP_TMP_DIR/install_wget.log
   tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
-  sudo mv conftest /usr/local/bin
+  $SUDO_CMDmv conftest /usr/local/bin
 }
 
 install_oras() {
@@ -723,7 +696,7 @@ install_oras() {
   curl -sLO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
   mkdir -p oras-install/
   tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
-  sudo mv oras-install/oras /usr/local/bin/
+  $SUDO_CMD mv oras-install/oras /usr/local/bin/
   rm -rf oras_${VERSION}_*.tar.gz oras-install/
   oras version
   if [ $? -ne 0 ]; then
@@ -734,7 +707,7 @@ install_oras() {
 
 install_jq() {
   log "Installing jq"
-  sudo apt-get install jq -y > $CHAINLOOP_TMP_DIR/install_jq.log
+  $SUDO_CMD apt-get install jq -y >$CHAINLOOP_TMP_DIR/install_jq.log
   if [ $? -ne 0 ]; then
     log_error "jq installation failed"
     return 1
@@ -743,7 +716,7 @@ install_jq() {
 
 install_ruby_restclient() {
   log "Installing Ruby rest-client"
-  sudo gem install rest-client > $CHAINLOOP_TMP_DIR/install_ruby_restclient.log
+  $SUDO_CMD gem install rest-client >$CHAINLOOP_TMP_DIR/install_ruby_restclient.log
   if [ $? -ne 0 ]; then
     log_error "rest-client installation failed"
     return 1
@@ -752,19 +725,19 @@ install_ruby_restclient() {
 
 install_yq() {
   log "Installing yq"
-  sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
+  $SUDO_CMD wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
   if [ $? -ne 0 ]; then
     log_error "yq installation failed"
     return 1
   fi
-  sudo chmod a+x /usr/local/bin/yq
+  $SUDO_CMD chmod a+x /usr/local/bin/yq
 }
 
 install_parlay() {
   log "Installing Parlay"
-  wget -q https://github.com/snyk/parlay/releases/latest/download/parlay_Linux_x86_64.tar.gz > $CHAINLOOP_TMP_DIR/install_parlay.log
+  wget -q https://github.com/snyk/parlay/releases/latest/download/parlay_Linux_x86_64.tar.gz >$CHAINLOOP_TMP_DIR/install_parlay.log
   tar -xvf parlay_Linux_x86_64.tar.gz
-  sudo mv parlay /usr/local/bin/
+  $SUDO_CMD mv parlay /usr/local/bin/
   rm parlay_Linux_x86_64.tar.gz
 }
 
@@ -797,155 +770,24 @@ install_chainloop_tools() {
 }
 
 
-process_metadata() {
-  log "Preparing metadata for $artifact"
-  case "$kind" in
-  # Each method should set pairs with the list of metadata to add to the attestation
-  "vac")
-    prepare_metadata_for_vac_artifact
-    ;;
-  "bitnami")
-    prepare_metadata_for_bitnami_artifact
-    ;;
-  "oci")
-    prepare_metadata_for_oci_artifact
-    ;;
-  "helm_chart")
-    prepare_metadata_for_helm_chart_artifact
-    ;;
-  *)
-    log_error "Unknown artifact kind: $kind"
-    return 1
-    ;;
-  esac
-  if [ $? -ne 0 ]; then
-    log_error "Failed to prepare metadata for $kind artifact"
-    return 1
-  fi
-  log "Preparing metadata for $artifact: DONE"
-
-  if [ $kind != "helm_chart" ] ; then
-    if [ ! -f spdx.json ]; then
-      syft -o spdx-json $uri > spdx.json
-    fi
-    if [ ! -f cyclonedx.json ]; then
-      syft -o cyclonedx-json $uri > cyclonedx.json
-    fi
-
-    parlay scorecard enrich cyclonedx.json | jq > cyclonedx-scorecard.json
-    parlay ecosystems enrich cyclonedx-scorecard.json | jq > cyclonedx-scorecard-ecosystems.json
-    parlay snyk enrich cyclonedx-scorecard-ecosystems.json | jq > cyclonedx-enriched.json
-  fi
-
-  for ((i = 0; i < ${#METADATA[@]}; i += 2)); do
-    k=${METADATA[i]}
-    v=${METADATA[i + 1]}
-    if [[ $v != *.* ]]; then
-      v=$(eval "echo \$$v")
-    fi
-
-    log "Adding ${k}=${v} to attestation"
-    chainloop attestation add --name "${k}" --value "${v}"
-    if [ $? -ne 0 ]; then
-      log_error "Failed to add ${k} to attestation"
-      return 1
-    fi
-  done
-}
-
-# chainloop_adapter_run "${args['kind']}" "${args['registry_uri']}" "${args['artifacts']}"
-chainloop_adapter_run() {
-  kind=$1
-  repo=$2
-  artifacts=$3
-
-  CHLP_TMPDIR="tmp/chainloop/adapter/${t}/${kind}/"
-
-  mkdir -p $CHLP_TMPDIR
-
-  # validations
-  if [[ ! $artifacts =~ ^[[:alnum:].,:-]+$ ]]; then
-    log_error "containers must be a comma-separated list of alphanumeric strings"
-    exit 1
-  fi
-
-  IFS=',' read -ra vals <<<"$artifacts"
-  for a in "${vals[@]}"; do
-    cdir=$(pwd)
-    tdir="${CHLP_TMPDIR}/$a"
-    mkdir -p "${tdir}"
-    cd "${tdir}"
-
-    # $repo
-    artifact=$a
-    uri="${repo}/${artifact}"
-    tag="latest"
-    app_id="${artifact}"
-    if [[ "$artifact" == *:* ]]; then
-      tag="${artifact##*:}"
-      app_id="${artifact%:*}"
-    fi
-    full_uri="${repo}/${app_id}:${tag}"
-    app_path="${kind}/${app_id}:${tag}"
-
-    # Save the original file descriptors for stdout (1) and stderr (2)
-    exec 3>&1 4>&2
-    # Redirect both stdout and stderr to a file and screen using tee
-    exec > >(tee "output.log") 2>&1
-
-    log_header "Processing ${kind} ${repo} - artifacts $artifacts"
-    log_header "  processing artifact: $app_id - $full_uri"
-    log "Initializing Chainloop Attestation"
-    chainloop attestation init
-    if [ $? -ne 0 ]; then
-      log_error "Chainloop initialization failed"
-      exit 1
-    fi
-
-    log "Initializing Chainloop Attestation: DONE"
-    process_metadata
-
-    if [ $? -ne 0 ]; then
-      log_error "Chainloop attestation failed."
-      chainloop attestation reset
-      # chainloop attestation reset --trigger cancellation
-      exit 1
-    fi
-    chainloop attestation status --full
-
-    # Restore the original file descriptors
-
-    exec 1>&3 2>&4
-    # Close the saved file descriptors
-    exec 3>&- 4>&-
-
-    chainloop attestation add --name log --value output.log
-
-    # chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY
-    chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY --annotation id=$app_id,path=$app_path
-
-    cd "${cdir}"
-  done
-}
-
 chainloop_attestation_add_from_yaml() {
   log "Adding Metadata files based on .chainloop.yml to attestation"
-  script=`cat .chainloop.yml | yq eval '.attestation[] | "chainloop attestation add --name "  + .name + " --value " + .path + "; "'`
+  script=$(cat .chainloop.yml | yq eval '.attestation[] | "chainloop attestation add --name "  + .name + " --value " + .path + " 2>&1; "')
   eval $script
 }
 
 chainloop_attestation_init() {
   log "Initializing Chainloop Attestation"
-  if [ -z "${CHAINLOOP_CONTRACT_REVISION+x}" ]; then
-    chainloop attestation init -f
+  if [ -z "${CHAINLOOP_CONTRACT_REVISION}" ]; then
+    chainloop attestation init -f 2>&1
   else
-    chainloop attestation init -f --contract-revision ${CHAINLOOP_CONTRACT_REVISION}
+    chainloop attestation init -f --contract-revision ${CHAINLOOP_CONTRACT_REVISION} 2>&1
   fi
 }
 
 chainloop_attestation_status() {
   log "Checking Attestation Status"
-  if chainloop attestation status --full &> c8-status.txt ; then
+  if chainloop attestation status --full &>c8-status.txt; then
     log "Attestation Status Process Completed Successfully"
     cat c8-status.txt
   else
@@ -958,65 +800,86 @@ chainloop_attestation_status() {
 
 chainloop_attestation_push() {
   log "Pushing Attestation"
-  if chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY &> c8-push.txt ; then
+  if [ -z "${CHAINLOOP_SIGNING_KEY_PATH+x}" ]; then
+    log "  with CHAINLOOP_SIGNING_KEY"
+    tmp_key="${CHAINLOOP_TMP_DIR}/key"
+    mkdir -p "${CHAINLOOP_TMP_DIR}"
+    echo "${CHAINLOOP_SIGNING_KEY}" >$tmp_key
+  else
+    log "  with CHAINLOOP_SIGNING_KEY_PATH"
+    tmp_key="${CHAINLOOP_SIGNING_KEY_PATH}"
+  fi
+  # chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY
+  if chainloop attestation push --key $tmp_key &>c8-push.txt; then
     log "Attestation Process Completed Successfully"
     cat c8-push.txt
+    rm $tmp_key
   else
     exit_code=$?
     log_error "Attestation Process Failed"
     cat c8-push.txt
+    rm $tmp_key
     return $exit_code
   fi
 }
 
+prepare_tmp_file() {
+  tmp_dir="${CHAINLOOP_TMP_DIR}"
+  file_name=$1
+  mkdir -p "${tmp_dir}"
+  t="${tmp_dir}/${file_name}"
+  if [ -f $t ]; then
+    log_error "TMP file $tmp_file already exists"
+    return 1
+  fi
+  echo $t
+}
+
 chainloop_summary() {
-  mkdir -p ${CHAINLOOP_TMP_DIR}
-  tmpfile="${CHAINLOOP_TMP_DIR}/report.txt"
-  digest=`cat c8-push.txt| grep " Digest: " | awk -F\  '{print $3}'`
-  echo -e "## Great job!\nYou are making SecOps and Compliance teams really happy. Keep up the good work!\n" >> $tmpfile
-  echo "**[Chainloop Trust Report](https://app.chainloop.dev/attestation/${digest})**" >> $tmpfile
-  echo "\`\`\`" >> $tmpfile
-  cat c8-status.txt >> $tmpfile
-  echo "\`\`\`" >> $tmpfile
+  tmpfile=$(prepare_tmp_file report.txt)
+  digest=$(cat c8-push.txt | grep " Digest: " | awk -F\  '{print $3}')
+  echo -e "## Great job!\n\nYou are making SecOps and Compliance teams really happy. Keep up the good work!\n" >>$tmpfile
+  echo "**[Chainloop Trust Report]( https://app.chainloop.dev/attestation/${digest} )**" >>$tmpfile
+  echo "\`\`\`" >>$tmpfile
+  cat c8-status.txt >>$tmpfile
+  echo "\`\`\`" >>$tmpfile
   cat $tmpfile
 }
 
 chainloop_generate_github_summary() {
   log "Generating GitHub Summary"
-  chainloop_summary >> $GITHUB_STEP_SUMMARY
+  chainloop_summary >>$GITHUB_STEP_SUMMARY
 }
 
 chainloop_summary_on_failure() {
-  mkdir -p ${CHAINLOOP_TMP_DIR}
-  tmpfile="${CHAINLOOP_TMP_DIR}/report_on_failure.txt"
-  echo -e "## Chainloop Attestation Failed\nWe were unable to complete the Chainloop attestation process due to unmet SecOps and Compliance requirements:" >> $tmpfile
+  tmpfile=$(prepare_tmp_file report_on_failure.txt)
+  echo -e "## Chainloop Attestation Failed\nWe were unable to complete the Chainloop attestation process due to unmet SecOps and Compliance requirements:" >>$tmpfile
   if [ -f c8-push.txt ]; then
-    echo -e "\n> [!WARNING]" >> $tmpfile
-    cat c8-push.txt | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" | sed 's/^/> /' >> $tmpfile
-    echo -e "\n" >> $tmpfile
+    echo -e "\n> [!WARNING]" >>$tmpfile
+    cat c8-push.txt | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" | sed 's/^/> /' >>$tmpfile
+    echo -e "\n" >>$tmpfile
   fi
   if [ -f c8-status.txt ]; then
-    echo "\`\`\`" >> $tmpfile
-    cat c8-status.txt | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" >> $tmpfile
-    echo "\`\`\`" >> $tmpfile
+    echo "\`\`\`" >>$tmpfile
+    cat c8-status.txt | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" >>$tmpfile
+    echo "\`\`\`" >>$tmpfile
   fi
   cat $tmpfile
 }
 
 chainloop_generate_github_summary_on_failure() {
   log "Generating GitHub Summary on Failure"
-  chainloop_summary_on_failure >> $GITHUB_STEP_SUMMARY
+  chainloop_summary_on_failure >>$GITHUB_STEP_SUMMARY
 }
 
 chainloop_collect_logs_for_github_jobs() {
   log "Collecting logs for GitHub Jobs"
-  # requires GH_TOKEN github.token
-
+  # GH_TOKEN or GITHUB_TOKEN is required for this to work
   # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#download-job-logs-for-a-workflow-run
   mkdir -p metadata/gh_logs
-  gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs > metadata/gh_logs/jobs.json
-  for j in `cat metadata/gh_logs/jobs.json | jq '.jobs[].id'` ; do
-    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/jobs/${j}/logs > metadata/gh_logs/${j}.log
+  gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs >metadata/gh_logs/jobs.json
+  for j in $(cat metadata/gh_logs/jobs.json | jq '.jobs[].id'); do
+    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/actions/jobs/${j}/logs >metadata/gh_logs/${j}.log
   done
 }
 
@@ -1024,12 +887,12 @@ install_chainloop_labs_cli() {
   log "Installing Chainloop Labs CLI"
   mkdir -p metadata
   branch=${1:-main}
-  sudo curl -sfL https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/c8l -o /usr/local/bin/c8l
+  $SUDO_CMD curl -sfL https://raw.githubusercontent.com/chainloop-dev/labs/${branch}/tools/c8l -o /usr/local/bin/c8l
   if [ $? -ne 0 ]; then
     log_error "Failed to install labs CLI"
     return 1
   fi
-  sudo chmod +x /usr/local/bin/c8l
+  $SUDO_CMD chmod +x /usr/local/bin/c8l
 }
 
 install_labs_helpers() {
@@ -1043,8 +906,11 @@ install_labs_helpers() {
 }
 
 install_chainloop_labs() {
-  logs "Installing Chainloop Labs"
+  log "Installing Chainloop Labs"
   branch=${1:-main}
+
+  mkdir -p ${CHAINLOOP_TMP_DIR}
+
   install_chainloop_labs_cli ${branch}
   install_labs_helpers ${branch}
 }
@@ -2050,6 +1916,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
